{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.serviceName }}-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eduhub.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: "{{ .Values.serviceName }}-secret"
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.parameters }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
  {{- end }}
{{- end }}