{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Values.serviceName }}-pdb"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eduhub.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "eduhub.selectorLabels" . | nindent 6 }}
{{- end }}